-   id: lams
    name: LAMS Looker linter
    description: https://github.com/looker-open-source/look-at-me-sideways
    entry: lams
    language: docker

-   id: lkmlstyle
    name: lkmlstyle
    description: https://github.com/spectacles-ci/lkmlstyle
    entry: lkmlstyle
    files: ^.*\.(lkml)$
    language: docker